name = "openmev-poolmonitor"
workers_dev = true
account_id = "25df8d18fce28bce3ded9a965ac20b80"
type = "webpack"
webpack_config = "node_modules/flareact/webpack"

[triggers]
crons = ["*/2 * * * *"]

[site]
bucket = "out"
entry-point = "./"

# uncomment and adjust following if you are not using GitHub Actions
#[env.production]
#kv-namespaces = [{binding="KV_STATUS_PAGE", id="681afb274f954f808e583c1ea41e283c", preview_id=""}]
#zone_id="xxx"
#route="xxx"
